# Generated by Django 4.2.5 on 2023-10-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_active_productline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productline',
            old_name='stike_qty',
            new_name='stoke_qty',
        ),
    ]
