# Generated by Django 4.2.5 on 2023-10-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_stike_qty_productline_stoke_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
